name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 11.x

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Test application
        run: npm run test
        env:
          CI: true
